# Utilisation de l'image officielle Node.js
FROM node:18

# Répertoire de travail
WORKDIR /app

# Copier les fichiers de dépendances
COPY package.json package-lock.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers frontend
COPY . .

# Construire l'application Angular
#RUN npm run build --prod

# Exposer le port de l'app auth
EXPOSE 4201

# Démarrer l'application auth
CMD ["npx", "nx", "run", "auth:serve", "--host", "0.0.0.0", "--disable-host-check"]